### PR TITLE
feat: immediates segment

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)

### CODE REVIEW

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul, @giladchase, and @shaharsamocha7)

___
*[`crates/runnair/src/vm/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-ODv_hrj4Gznt8OeV7JF:-ODv_hrj4Gznt8OeV7JG:b-fxtoo1) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/eb05538dcec1179440133c9477a00506decbbc13/crates/runnair/src/vm/mod.rs#L34)):*
> ```XML
> // TODO: reconsider input type and parsing.
> pub(crate) type Input = serde_json::Value;
> const IMMEDIATES_SEGMENT: Segment = MAX_MEMORY_SIZE_BITS - 1;
> ```

This is segment 29, right? We might get to it naturally, immediates should be a segment you never get to, maybe 2^32-1 or something like that.
___
*[`crates/runnair/src/vm/assert.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-ODv_LBJBC9JgKjuQWdC:-ODv_LBJBC9JgKjuQWdD:bpd1cly) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/eb05538dcec1179440133c9477a00506decbbc13/crates/runnair/src/vm/assert.rs#L163)):*
> ```XML
> define_assert!(ap, fp, ap);
> define_assert!(ap, fp, fp);
> define_assert!(ap, imm, ap);
> ```

Nice, this looks much better!

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)* status: all files reviewed, 2 unresolved discussions (waiting on @Alon-Ti, @giladchase, and @shaharsamocha7)

___
*[`crates/runnair/src/vm/assert.rs` line 163 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-ODv_LBJBC9JgKjuQWdC:-ODvatXp-5TGNnWyd68p:b32vhw) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/eb05538dcec1179440133c9477a00506decbbc13/crates/runnair/src/vm/assert.rs#L163)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Nice, this looks much better!
</blockquote></details>

:)

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)* status: all files reviewed, 1 unresolved discussion (waiting on @Alon-Ti, @giladchase, and @shaharsamocha7)

___
*[`crates/runnair/src/vm/mod.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-ODv_hrj4Gznt8OeV7JF:-OE84IpzCINnrbMNL7jA:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/eb05538dcec1179440133c9477a00506decbbc13/crates/runnair/src/vm/mod.rs#L34)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

This is segment 29, right? We might get to it naturally, immediates should be a segment you never get to, maybe 2^32-1 or something like that.
</blockquote></details>

Done.

**Review by giladchase — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/runnair/src/vm/assert.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-OE8G5zf6qOMg5P9UlPM:-OE8G5zgAFWDsXNKx2w1:bd13irs) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/7554963f8eba6292d45d590a0d13e8cbb371f364/crates/runnair/src/vm/assert.rs#L75)):*
> ```XML
>     ($dest:ident, $op1:ident, $op2:ident) => {
>         paste! {
>             /// Assert add without incrementing `ap`: `assert_[ap/fp]_add_[ap/fp/imm]_[ap/fp]`.
> ```

Where does the `imm` come into play here?



_Code quote:_
```XML
            /// Assert add without incrementing `ap`: `assert_[ap/fp]_add_[ap/fp/imm]_[ap/fp]`.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti and @shaharsamocha7)

___
*[`crates/runnair/src/vm/assert.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-OE8G5zf6qOMg5P9UlPM:-OE8PrG03mdQcCxpfJWr:b83thbn) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/7554963f8eba6292d45d590a0d13e8cbb371f364/crates/runnair/src/vm/assert.rs#L75)):*
<details><summary><i>Previously, giladchase wrote…</i></summary><blockquote>

Where does the `imm` come into play here?
</blockquote></details>

Not sure I understand the Q; the second argument of the instruction can be an immediate (const) value.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/31#-:-OE8UQ6i9bdUOjHQMKU1:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shaharsamocha7)

**Pull request merged**
