### PR TITLE
feat: support fibonacci claim index assignment hint

### PR DESCRIPTION
**Pull request by elintul**
Only trivial format for now (JSON); to-be-expanded.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26)

### CODE REVIEW

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/runnair/tests/data/fibonacci_compiled.json` line 701 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26#-ODkbpRX3gUQNhLpqBph:-ODkbpRY34DZ9aPiHPab:b-5yzl82) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/c9fdebc2dad9ece32b47424d5e539fa1c5be7809/crates/runnair/tests/data/fibonacci_compiled.json#L701)):*
> ```JSON
>                     "__main__.main"
>                 ],
>                 "code": "\"FibonnaciIndex\"",
> ```

JSON formatting for now, so that [this](https://github.com/starkware-libs/stwo-cairo-m31/blob/c9fdebc2dad9ece32b47424d5e539fa1c5be7809/crates/runnair/src/vm/mod.rs#L114) works.



_Code quote:_
```JSON
"\"FibonnaciIndex\""
```

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26)* status: all files reviewed, 2 unresolved discussions (waiting on @elintul)

___
*[`crates/runnair/src/vm/hints.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26#-ODkewxN7dx4RnFicOGX:-ODkewxO5jOz05Td1mFa:bzg7j9i) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/c9fdebc2dad9ece32b47424d5e539fa1c5be7809/crates/runnair/src/vm/hints.rs#L31)):*
> ```XML
> #[derive(Debug)]
> pub(crate) struct HintRunner {
>     pc_to_hint: HashMap<M31, Hint>,
> ```

Change to Vec for efficiency

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Alon-Ti)

___
*[`crates/runnair/src/vm/hints.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26#-ODkewxN7dx4RnFicOGX:-ODkmo9TDlFwAfspABf8:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/c9fdebc2dad9ece32b47424d5e539fa1c5be7809/crates/runnair/src/vm/hints.rs#L31)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Change to Vec for efficiency
</blockquote></details>

Done.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/26#-:-ODl7J9j5jyCPCdpqxGg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
