### PR TITLE
feat: implement `assert_[ap/fp]_add_[ap/fp]_[ap/fp][_appp]` instructions

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4)

### CODE REVIEW

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4)* status: all files reviewed, 3 unresolved discussions (waiting on @elintul)

___
*[`runnair/crates/runner/src/vm/assert.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD1NuNXCbgBsM7LShLh:-OD1NuNXCbgBsM7LShLi:bijca1z) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0d96d6304cd1a2eef848e3566ea8b010b992d488/runnair/crates/runner/src/vm/assert.rs#L7)):*
> ```XML
> use crate::vm::{InstructionArgs, State};
> 
> fn resolve_addresses(state: State, bases: &[&str], offsets: &[M31]) -> Vec<MaybeRelocatableAddr> {
> ```

Consider adding a length parameter N and then having a generic function, something like
`fn resolve_addresses<const N: usize>(state: State, bases: [&str; N], offsets: [M31; N]) -> [MaybeRelocatableAddr; N]`
to ensure type safety at compile time.
___
*[`runnair/crates/runner/src/vm/assert.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD1PmQO-WQya73To6_6:-OD1PmQO-WQya73To6_7:b-vhk31y) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0d96d6304cd1a2eef848e3566ea8b010b992d488/runnair/crates/runner/src/vm/assert.rs#L33)):*
> ```XML
> }
> 
> fn assign_or_assert_on_memory(
> ```

Add the word `add` somewhere in the name.
___
*[`runnair/crates/runner/src/vm/assert.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD1QHnp68lTcZk75aZv:-OD1QHnp68lTcZk75aZw:b-lrvt32) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0d96d6304cd1a2eef848e3566ea8b010b992d488/runnair/crates/runner/src/vm/assert.rs#L64)):*
> ```XML
>     ($dest:ident, $op1:ident, $op2:ident) => {
>         paste! {
>             /// Function without incrementing `ap`.
> ```

`/// assert_[ap/fp]_add_[ap/fp]_[ap/fp]`
Same below



_Code quote:_
```XML
/// Function without incrementing `ap`.
```

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Alon-Ti)

___
*[`runnair/crates/runner/src/vm/assert.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD1NuNXCbgBsM7LShLh:-OD20t6uDhpf2ppCVTRi:b-gn36df) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0d96d6304cd1a2eef848e3566ea8b010b992d488/runnair/crates/runner/src/vm/assert.rs#L7)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Consider adding a length parameter N and then having a generic function, something like
`fn resolve_addresses<const N: usize>(state: State, bases: [&str; N], offsets: [M31; N]) -> [MaybeRelocatableAddr; N]`
to ensure type safety at compile time.
</blockquote></details>

Done, very cool!
Tried to also assert `N <= 3` in compile time, but nothing supported in current stable Rust. :(
___
*[`runnair/crates/runner/src/vm/assert.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD1PmQO-WQya73To6_6:-OD20UGLC5IFpudnbt-K:b-dkvvt4) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0d96d6304cd1a2eef848e3566ea8b010b992d488/runnair/crates/runner/src/vm/assert.rs#L33)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Add the word `add` somewhere in the name.
</blockquote></details>

Done, but planning on generalizing to `mul`.
___
*[`runnair/crates/runner/src/vm/assert.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD1QHnp68lTcZk75aZv:-OD20Riq6p7TliSoqmr1:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0d96d6304cd1a2eef848e3566ea8b010b992d488/runnair/crates/runner/src/vm/assert.rs#L64)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

`/// assert_[ap/fp]_add_[ap/fp]_[ap/fp]`
Same below
</blockquote></details>

Done.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @Alon-Ti)

___
*[`runnair/crates/runner/src/vm/assert.rs` line 17 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-OD28Tuf8e9c0N81ZVch:-OD28Tug9WuJS9ygacDu:b-xweosr) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/0c1f18d761da387705e1a0f30d9739168abaf202/runnair/crates/runner/src/vm/assert.rs#L17)):*
> ```XML
>     );
> 
>     std::array::from_fn(|i| {
> ```

Most elegant construction I could find, although uses indices. :(



_Code quote:_
```XML
std::array::from_fn(|i| {
```

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/4#-:-OD2BgR--zlIzIMg0MZj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
