### PR TITLE
feat: support multiplication in assert instructions

### PR DESCRIPTION
**Pull request by elintul**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13)

### CODE REVIEW

**Review by Alon-Ti — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13)* status: all files reviewed, 1 unresolved discussion (waiting on @elintul)

___
*[`crates/runnair/src/vm/assert.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13#-ODC0YjHDOJ_jHK2ANDF:-ODC0YjI9x9rVK7eLEjM:b-8bmyps) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/6f8367b271d612b939fe4f30808725166b03ad21/crates/runnair/src/vm/assert.rs#L22)):*
> ```XML
>     let [dest_addr, op1_addr, op2_addr] = resolve_addresses(state, &[dest, op1, op2], args);
> 
>     let apply = match operation {
> ```

Make `apply` and `deduce` methods of `Operation`.

**Review by elintul — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @Alon-Ti)

___
*[`crates/runnair/src/vm/assert.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13#-ODC0YjHDOJ_jHK2ANDF:-ODC9yLL3oDZpGi_Yx5A:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo-m31/blob/6f8367b271d612b939fe4f30808725166b03ad21/crates/runnair/src/vm/assert.rs#L22)):*
<details><summary><i>Previously, Alon-Ti wrote…</i></summary><blockquote>

Make `apply` and `deduce` methods of `Operation`.
</blockquote></details>

Done.

**Review by Alon-Ti — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13#-:-ODCATpg3PpISScpm81i:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Review by Alon-Ti — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo-m31/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @elintul)

**Pull request merged**
